// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiverBooks.Books;

#nullable disable

namespace RiverBooks.Books.Data.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20251029070528_BooksDataSeeding")]
    partial class BooksDataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Books")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RiverBooks.Books.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books", "Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("34125d61-9ae7-4dda-994b-d9623b3fbcff"),
                            Author = "Robert C. Martin",
                            Price = 10.99m,
                            Title = "Clean Architecture"
                        },
                        new
                        {
                            Id = new Guid("66b37ca5-6445-4da8-bac2-4896b9273a8c"),
                            Author = "Eric Evans",
                            Price = 11.99m,
                            Title = "Domain-Driven Design"
                        },
                        new
                        {
                            Id = new Guid("2dd04ba1-81b5-4a2b-b5d7-d9a8520628e1"),
                            Author = "Vaughn Vernon",
                            Price = 12.99m,
                            Title = "Implementing Domain-Driven Design"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
